// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// LogitProbs
Eigen::VectorXd LogitProbs(Eigen::MatrixXd X, Eigen::VectorXd Y);
RcppExport SEXP _GeneEnvInteractions_LogitProbs(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(LogitProbs(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// PermLogitProbs
Eigen::MatrixXd PermLogitProbs(Eigen::MatrixXd X, Eigen::MatrixXd Y0);
RcppExport SEXP _GeneEnvInteractions_PermLogitProbs(SEXP XSEXP, SEXP Y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y0(Y0SEXP);
    rcpp_result_gen = Rcpp::wrap(PermLogitProbs(X, Y0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GeneEnvInteractions_LogitProbs", (DL_FUNC) &_GeneEnvInteractions_LogitProbs, 2},
    {"_GeneEnvInteractions_PermLogitProbs", (DL_FUNC) &_GeneEnvInteractions_PermLogitProbs, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GeneEnvInteractions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
