# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogitProbs <- function(X, Y) {
    .Call('_GeneEnvInteractions_LogitProbs', PACKAGE = 'GeneEnvInteractions', X, Y)
}

PermLogitProbs <- function(X, Y0) {
    .Call('_GeneEnvInteractions_PermLogitProbs', PACKAGE = 'GeneEnvInteractions', X, Y0)
}

